# Generated by Django 3.2.9 on 2021-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msngr', '0006_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='msngr.Profile'),
        ),
    ]
