# Generated by Django 3.2.9 on 2021-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msngr', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
